# Hello, this is configuration file ;)
# Delete symbol "#" for activating function


# debug_path
# The path must end with "\"
# Dsefault log file(escort.log) save in folder with program

debug_level debug
# Description: function for write logs
#	debug: Output all messages to the console and write them to the log file
#	info (by default): Output only informational messages (including errors) to the console and save them to a log file
#	warning: 
#	error (In development): Output to the console only errors (including critical ones) and save them to the log file.
#	critical: Output to the console only errors that prevent the application from working and save them to the log file

bot_token ESCORT_TELEGRAM_BOT_TOKEN
chat_id ESCORT_TELEGRAM_CHAT_ID
# Description: Bot Telegram Token
# you can add a bot token and leave the chat id field empty. 
# Then the bot will send you the chat id on command /start
# Ling for find chat_id after /start
# replace <YourBOTToken>
# https://api.telegram.org/bot<YourBOTToken>/getUpdates

# nc-token test
# nextcloud_url
# Description: Data for using the nextcloud API
# Use the link to get the json file

ssh_log_path D:\your path\file.log
# Description: Path to the ssh log file
